"""
Report Generator
=================
Generates markdown reports for search results, bill summaries, and watchlist status.
"""

from __future__ import annotations

from datetime import datetime


class ReportGenerator:
    """Generates markdown reports for the Legislative Tracker."""

    @staticmethod
    def search_report(query: str, state: str, year: int, results: list[dict]) -> str:
        """Generate a markdown report of search results."""
        lines = [
            f"# Legislative Search Report",
            f"",
            f"**Query:** {query}",
            f"**Jurisdiction:** {state}",
            f"**Year:** {year or 'Current session'}",
            f"**Results:** {len(results)} bills found",
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            f"",
            f"---",
            f"",
        ]

        if not results:
            lines.append("No bills found matching the query.")
            return "\n".join(lines)

        lines.append("| # | Bill | State | Status | Last Action | Date |")
        lines.append("|---|------|-------|--------|-------------|------|")

        for i, bill in enumerate(results, 1):
            number = bill.get("number", "N/A")
            title = bill.get("title", "")
            if len(title) > 60:
                title = title[:57] + "..."
            state_code = bill.get("state", "")
            status = bill.get("status", "")
            last_action = bill.get("last_action", "")
            if len(last_action) > 40:
                last_action = last_action[:37] + "..."
            date = bill.get("last_action_date", "")
            url = bill.get("url", "")

            bill_link = f"[{number}]({url})" if url else number
            lines.append(f"| {i} | {bill_link} — {title} | {state_code} | {status} | {last_action} | {date} |")

        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("*Report generated by Legislative Tracker (AI-Powered PA Toolkit). "
                      "Bill status may have changed since generation. Verify before external use.*")

        return "\n".join(lines)

    @staticmethod
    def bill_summary_report(
        bill_detail: dict,
        bill_header: str,
        ai_summary: str,
        *,
        summary_status: str = "verified",
        caveats: list[str] | None = None,
    ) -> str:
        """Combine bill header and AI summary into a full report."""
        caveats = caveats or []
        lines = [
            f"# Bill Summary: {bill_detail.get('number', 'N/A')} — {bill_detail.get('title', 'N/A')}",
            f"",
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            f"**Risk Level:** Yellow — requires human review before distribution",
            f"**Summary Status:** {summary_status}",
            f"",
            f"---",
            f"",
            bill_header,
            f"",
            f"---",
            f"",
        ]

        if summary_status in {"verified", "preview_ready"}:
            lines.append(ai_summary or "_No verified source summary was generated._")
        else:
            lines.append("## Summary Unavailable")
            lines.append("")
            lines.append("A verified source summary could not be generated from the official bill text.")
            if caveats:
                lines.append("")
                lines.append("### Diagnostics")
                for caveat in caveats:
                    lines.append(f"- {caveat}")

        lines.extend([
            f"",
            f"---",
            f"",
            f"*Report generated by Legislative Tracker (AI-Powered PA Toolkit). "
            f"AI-generated content requires human review before external distribution.*",
        ])
        return "\n".join(lines)

    @staticmethod
    def watchlist_report(bills: list[dict], refresh_results: list[dict] = None) -> str:
        """Generate a watchlist status report."""
        lines = [
            f"# Legislative Watchlist",
            f"",
            f"**Bills tracked:** {len(bills)}",
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            f"",
            f"---",
            f"",
        ]

        if not bills:
            lines.append("No bills in watchlist. Use `--watchlist add --bill-id <ID>` to add bills.")
            return "\n".join(lines)

        # If we have refresh results, highlight changes
        if refresh_results:
            changed = [r for r in refresh_results if r.get("changed")]
            if changed:
                lines.append(f"### Status Changes Detected ({len(changed)})")
                lines.append("")
                for r in changed:
                    lines.append(f"- **{r['number']}** ({r['state']}): "
                                 f"{r.get('old_status', '?')} → **{r.get('new_status', '?')}**")
                    if r.get("new_action") != r.get("old_action"):
                        lines.append(f"  - New action: {r.get('new_action', '')}")
                lines.append("")
                lines.append("---")
                lines.append("")
            else:
                lines.append("*No status changes since last check.*")
                lines.append("")

        lines.append("| Bill | State | Status | Last Action | Date | Tracked Since |")
        lines.append("|------|-------|--------|-------------|------|---------------|")

        for bill in bills:
            number = bill.get("number", "N/A")
            url = bill.get("url", "")
            bill_link = f"[{number}]({url})" if url else number
            state = bill.get("state", "")
            status = bill.get("status", "")
            last_action = bill.get("last_action", "")
            if len(last_action) > 40:
                last_action = last_action[:37] + "..."
            date = bill.get("last_action_date", "")
            added = bill.get("added_at", "")[:10]

            lines.append(f"| {bill_link} | {state} | {status} | {last_action} | {date} | {added} |")

        return "\n".join(lines)
