export const TOUR_STORAGE_KEY = 'strategitect_guided_tour_completed';

export const REVIEWER_TOUR_ID = 'reviewer-tour';

export const TOOL_TOUR_IDS = {
  backgroundMemo: 'tool-background-memo',
  hearingMemo: 'tool-hearing-memo',
  influenceTracker: 'tool-influence-tracker',
  legislativeTracker: 'tool-legislative-tracker',
  mediaClips: 'tool-media-clips',
  mediaList: 'tool-media-list',
  messagingMatrix: 'tool-messaging-matrix',
  remy: 'tool-remy',
  stakeholderBriefing: 'tool-stakeholder-briefing',
  stakeholderMap: 'tool-stakeholder-map',
};

function buildToolTour({ id, title, route, introTarget, introBody, inputTarget, inputTitle, inputBody, optionalTarget, optionalTitle, optionalBody, submitTarget, submitBody, outputTarget, outputBody }) {
  return {
    id,
    label: title,
    steps: [
      {
        id: `${id}-intro`,
        route,
        target: introTarget,
        title,
        body: introBody,
        placement: 'bottom',
      },
      {
        id: `${id}-input`,
        route,
        target: inputTarget,
        title: inputTitle,
        body: inputBody,
        placement: 'bottom',
      },
      {
        id: `${id}-optional`,
        route,
        target: optionalTarget,
        title: optionalTitle,
        body: optionalBody,
        placement: 'left',
      },
      {
        id: `${id}-submit`,
        route,
        target: submitTarget,
        title: 'Run it yourself',
        body: submitBody,
        placement: 'top',
      },
      {
        id: `${id}-output`,
        route,
        target: outputTarget,
        title: 'Output surface',
        body: outputBody,
        placement: 'top',
      },
    ],
  };
}

export const TOUR_DEFINITIONS = {
  [REVIEWER_TOUR_ID]: {
    id: REVIEWER_TOUR_ID,
    label: 'Guided Reviewer Tour',
    steps: [
      {
        id: 'dashboard-overview',
        route: '/app',
        target: 'dashboard-overview',
        title: 'How the prototype is organized',
        body: 'These sections group tools by workflow stage: intelligence gathering, stakeholder preparation, and output creation.',
        placement: 'bottom',
      },
      {
        id: 'dashboard-background-memo',
        route: '/app',
        target: 'background-memo-card',
        title: 'Recommended starting point',
        body: 'Background Memo is the fastest review path because the input is simple and the output shows the system logic clearly.',
        placement: 'right',
      },
      {
        id: 'background-subject',
        route: '/app/background-memo',
        target: 'background-memo-subject',
        title: 'Start with a clear subject',
        body: 'Use an organization, issue, or person. Broad but recognizable entries like "NATO" or "Pfizer" work well for a first run.',
        placement: 'bottom',
      },
      {
        id: 'background-sections',
        route: '/app/background-memo',
        target: 'background-memo-sections',
        title: 'Define the memo structure',
        body: 'Write one section per line. This tells the tool how to organize the briefing instead of changing the underlying research logic.',
        placement: 'right',
      },
      {
        id: 'background-options',
        route: '/app/background-memo',
        target: 'background-memo-options',
        title: 'Optional grounding inputs',
        body: 'Context, source files, and disclosure settings deepen the memo, but they are not required for a simple reviewer demo.',
        placement: 'left',
      },
      {
        id: 'background-submit',
        route: '/app/background-memo',
        target: 'background-memo-submit',
        title: 'Run the pipeline manually',
        body: 'The tour never submits for you. When you are ready, this button starts the backend job with exactly the inputs you entered.',
        placement: 'top',
      },
      {
        id: 'background-output',
        route: '/app/background-memo',
        target: 'background-memo-output',
        title: 'What appears after a run',
        body: 'Status, generated memo content, downloads, and supporting materials show up here. Outputs remain review-required before external use.',
        placement: 'top',
      },
      {
        id: 'tour-complete',
        route: '/app/background-memo',
        title: 'Tour complete',
        body: 'You can now run Background Memo, return to the dashboard, or explore the rest of the toolkit and Remy freely.',
        placement: 'center',
      },
    ],
  },
  [TOOL_TOUR_IDS.backgroundMemo]: {
    id: TOOL_TOUR_IDS.backgroundMemo,
    label: 'Background Memo Tour',
    steps: [
      {
        id: 'background-memo-intro',
        route: '/app/background-memo',
        target: 'background-memo-title-heading',
        title: 'What this tool does',
        body: 'Background Memo creates a structured briefing on an organization, issue, or person, using your requested sections and any supporting materials you provide.',
        placement: 'bottom',
      },
      {
        id: 'background-memo-subject-step',
        route: '/app/background-memo',
        target: 'background-memo-subject',
        title: 'Choose the subject',
        body: 'Enter the organization, issue, or person the memo should focus on.',
        placement: 'bottom',
      },
      {
        id: 'background-memo-date-step',
        route: '/app/background-memo',
        target: 'background-memo-date',
        title: 'Set the memo date',
        body: 'This date is carried into the memo output and helps frame the briefing in time.',
        placement: 'bottom',
      },
      {
        id: 'background-memo-sections-step',
        route: '/app/background-memo',
        target: 'background-memo-sections',
        title: 'Define the memo sections',
        body: 'Write one section per line so the memo has the structure you want.',
        placement: 'right',
      },
      {
        id: 'background-memo-context-step',
        route: '/app/background-memo',
        target: 'background-memo-context',
        title: 'Add additional context',
        body: 'Use this box for key angles, facts, or notes you want the memo to reflect.',
        placement: 'right',
      },
      {
        id: 'background-memo-files-step',
        route: '/app/background-memo',
        target: 'background-memo-source-files',
        title: 'Attach source files',
        body: 'You can upload articles, reports, transcripts, or other files to ground the memo in source material.',
        placement: 'left',
      },
      {
        id: 'background-memo-disclosures-step',
        route: '/app/background-memo',
        target: 'background-memo-options',
        title: 'Choose disclosure search options',
        body: 'Use these settings to pull lobbying, foreign agent, or nonprofit filing data into the memo research. You can also override the filing name if the official disclosure records use a different entity name than the memo subject.',
        placement: 'left',
      },
      {
        id: 'background-memo-run-step',
        route: '/app/background-memo',
        target: 'background-memo-submit',
        title: 'Generate the memo',
        body: 'This button runs the memo pipeline. The tour stays passive and never submits for you.',
        placement: 'top',
      },
      {
        id: 'background-memo-generated-step',
        route: '/app/background-memo',
        title: 'Review the generated memo',
        body: 'After completion, the memo appears here with the overview, fast facts, and the sections you requested.',
        placement: 'center',
        image: '/background-memo-tour-generated-memo.png',
        imageAlt: 'Background Memo generated memo screenshot',
      },
      {
        id: 'background-memo-downloads-step',
        route: '/app/background-memo',
        title: 'Downloads, articles, and disclosure data',
        body: 'This final area gives you the memo downloads, the articles used for research, and the raw disclosure data and disclosure file downloads when you requested them.',
        placement: 'center',
        image: '/background-memo-tour-downloads-and-research.png',
        imageAlt: 'Background Memo downloads and research drawer screenshot',
      },
    ],
  },
  [TOOL_TOUR_IDS.hearingMemo]: {
    id: TOOL_TOUR_IDS.hearingMemo,
    label: 'Hearing Memo Tour',
    steps: [
      {
        id: 'hearing-memo-intro',
        route: '/app/memos',
        target: 'hearing-memo-title-heading',
        title: 'What this tool does',
        body: 'Hearing Memo turns a transcript source into a structured first-draft hearing memo with verification outputs and downloadable files.',
        placement: 'bottom',
      },
      {
        id: 'hearing-memo-transcript',
        route: '/app/memos',
        target: 'hearing-memo-source',
        title: 'Upload the hearing transcript',
        body: 'The most reliable path is uploading the hearing transcript directly as a PDF or TXT file.',
        placement: 'bottom',
      },
      {
        id: 'hearing-memo-youtube-step',
        route: '/app/memos',
        target: 'hearing-memo-youtube',
        title: 'Or use a YouTube URL',
        body: 'You can also paste a YouTube link and let the tool fetch the transcript automatically, but this is usually less precise than uploading the transcript yourself.',
        placement: 'bottom',
      },
      {
        id: 'hearing-memo-header-step',
        route: '/app/memos',
        target: 'hearing-memo-header',
        title: 'Header fields',
        body: 'These fields shape the memo header, including who the memo is from, the memo date, and the subject line if you want to override the detected version.',
        placement: 'left',
      },
      {
        id: 'hearing-memo-advanced-step',
        route: '/app/memos',
        target: 'hearing-memo-options',
        title: 'Advanced options',
        body: 'Advanced options let you override hearing metadata such as title, committee, date, time, and the confidentiality footer.',
        placement: 'top',
      },
      {
        id: 'hearing-memo-run-step',
        route: '/app/memos',
        target: 'hearing-memo-submit',
        title: 'Generate the memo',
        body: 'This starts the four-stage pipeline. The tour stays passive and never runs it for you.',
        placement: 'top',
      },
      {
        id: 'hearing-memo-preview-step',
        route: '/app/memos',
        title: 'Memo preview',
        body: 'After completion, the memo appears here with the header, hearing overview, and the generated section-by-section write-up.',
        placement: 'center',
        image: '/hearing-memo-tour-preview.png',
        imageAlt: 'Hearing Memo preview screenshot',
      },
      {
        id: 'hearing-memo-downloads-step',
        route: '/app/memos',
        title: 'Download options',
        body: 'The completed run gives you the memo as DOCX, a plain-text version, and the verification JSON for review and export.',
        placement: 'center',
        image: '/hearing-memo-tour-downloads.png',
        imageAlt: 'Hearing Memo downloads screenshot',
      },
    ],
  },
  [TOOL_TOUR_IDS.influenceTracker]: {
    id: TOOL_TOUR_IDS.influenceTracker,
    label: 'Influence Tracker Tour',
    steps: [
      {
        id: 'influence-tracker-intro',
        route: '/app/influence',
        target: 'influence-tracker-title-heading',
        title: 'What this tool does',
        body: 'Influence Disclosure Tracker searches lobbying, foreign agent, and nonprofit disclosure records, then turns the matches into a report plus filterable data tables.',
        placement: 'bottom',
      },
      {
        id: 'influence-tracker-entities',
        route: '/app/influence',
        target: 'influence-tracker-entities',
        title: 'Entities to search',
        body: 'Enter the organization, company, nonprofit, or other entity you want to investigate. This is the anchor for the disclosure search.',
        placement: 'bottom',
      },
      {
        id: 'influence-tracker-scope',
        route: '/app/influence',
        target: 'influence-tracker-scope',
        title: 'Search scope',
        body: 'Choose whether to search for the entity as a client, as a lobbying firm or registrant, or both. This changes where the tool looks for matches.',
        placement: 'bottom',
      },
      {
        id: 'influence-tracker-years',
        route: '/app/influence',
        target: 'influence-tracker-years',
        title: 'Filing years',
        body: 'Limit the search to specific filing years, or use all available years when you want the widest historical view.',
        placement: 'bottom',
      },
      {
        id: 'influence-tracker-quarters',
        route: '/app/influence',
        target: 'influence-tracker-quarters',
        title: 'Quarters',
        body: 'These quarter toggles control which parts of the filing calendar are included in the search.',
        placement: 'bottom',
      },
      {
        id: 'influence-tracker-sources',
        route: '/app/influence',
        target: 'influence-tracker-sources',
        title: 'Data sources',
        body: 'Select which disclosure systems to search: LDA lobbying filings, FARA foreign agent records, and IRS 990 nonprofit filings.',
        placement: 'bottom',
      },
      {
        id: 'influence-tracker-run',
        route: '/app/influence',
        target: 'influence-tracker-submit',
        title: 'Run the search',
        body: 'This launches the disclosure query. The tour stays passive and never runs the tool automatically.',
        placement: 'top',
      },
      {
        id: 'influence-tracker-filtering',
        route: '/app/influence',
        title: 'Filter the matched entities',
        body: 'After a run, this review step lets you keep or remove matched clients and registrants before they are included in the report and tables.',
        placement: 'center',
        image: '/influence-tracker-tour-entity-filtering.png',
        imageAlt: 'Influence Tracker matched entity filtering screenshot',
      },
      {
        id: 'influence-tracker-summary-report',
        route: '/app/influence',
        title: 'Read the report summary first',
        body: 'The report opens with the disclosure tracker overview and the executive summary. These first sections tell you who was queried, the timeframe, the search scope, and the top-level findings before you move into source-specific details.',
        placement: 'center',
        image: '/influence-tracker-tour-summary-report.png',
        imageAlt: 'Influence Tracker summary report screenshot',
      },
      {
        id: 'influence-tracker-lda-activity',
        route: '/app/influence',
        title: 'LDA lobbying activity by firm',
        body: 'This section summarizes lobbying activity by firm and shows quarterly spending, filing type, and direct links back to the original filings.',
        placement: 'center',
        image: '/influence-tracker-tour-lda-activity.png',
        imageAlt: 'Influence Tracker LDA lobbying activity by firm screenshot',
      },
      {
        id: 'influence-tracker-lda-issues',
        route: '/app/influence',
        title: 'Issues lobbied',
        body: 'This section shows the issue areas, lobbying descriptions, and the government entities involved in those lobbying efforts.',
        placement: 'center',
        image: '/influence-tracker-tour-lda-issues.png',
        imageAlt: 'Influence Tracker issues lobbied screenshot',
      },
      {
        id: 'influence-tracker-lda-lobbyists',
        route: '/app/influence',
        title: 'Registered lobbyists',
        body: 'Here you can review the registered lobbyists tied to the matched filings, including former government positions when those are disclosed.',
        placement: 'center',
        image: '/influence-tracker-tour-lda-lobbyists.png',
        imageAlt: 'Influence Tracker registered lobbyists screenshot',
      },
      {
        id: 'influence-tracker-lda-tables',
        route: '/app/influence',
        title: 'LDA data tables, filters, and downloads',
        body: 'The LDA tables can be expanded, filtered column by column, and downloaded. Use the table filters to narrow what you are reviewing before exporting CSVs.',
        placement: 'center',
        image: '/influence-tracker-tour-lda-tables-filtered.png',
        imageAlt: 'Influence Tracker LDA data tables with filters screenshot',
      },
      {
        id: 'influence-tracker-fara-report',
        route: '/app/influence',
        title: 'FARA report details',
        body: 'The FARA section summarizes foreign agent records, principals, status, and filed documents. When available, you can open the linked original documentation directly from the report.',
        placement: 'center',
        image: '/influence-tracker-tour-fara-report.png',
        imageAlt: 'Influence Tracker FARA report screenshot',
      },
      {
        id: 'influence-tracker-fara-tables',
        route: '/app/influence',
        title: 'FARA tables',
        body: 'These tables organize foreign principals and document records into filterable datasets, with CSV downloads for further review.',
        placement: 'center',
        image: '/influence-tracker-tour-fara-tables.png',
        imageAlt: 'Influence Tracker FARA tables screenshot',
      },
      {
        id: 'influence-tracker-irs-report',
        route: '/app/influence',
        title: 'IRS 990 report details',
        body: 'The 990 section summarizes nonprofit filing history, finances, and matching confidence. When a filing PDF is available, you can open the original document from the report.',
        placement: 'center',
        image: '/influence-tracker-tour-irs-report.png',
        imageAlt: 'Influence Tracker IRS 990 report screenshot',
      },
      {
        id: 'influence-tracker-irs-tables',
        route: '/app/influence',
        title: 'IRS 990 tables',
        body: 'The IRS 990 data tables collect filing history into a filterable, downloadable format so you can inspect years, forms, and financial figures quickly.',
        placement: 'center',
        image: '/influence-tracker-tour-irs-tables.png',
        imageAlt: 'Influence Tracker IRS 990 tables screenshot',
      },
    ],
  },
  [TOOL_TOUR_IDS.legislativeTracker]: {
    id: TOOL_TOUR_IDS.legislativeTracker,
    label: 'Legislative Tracker Tour',
    steps: [
      {
        id: 'legislative-tracker-intro',
        route: '/app/legislative',
        target: 'legislative-tracker-title-heading',
        title: 'What this tool does',
        body: 'Legislative Tracker searches federal or state bills, lets you preview or deeply summarize the most relevant ones, and then save important bills to a live watchlist.',
        placement: 'bottom',
      },
      {
        id: 'legislative-tracker-search-mode',
        route: '/app/legislative',
        target: 'legislative-tracker-search-mode',
        title: 'Broad search or exact title match',
        body: 'Use Broad Search when you want to discover relevant bills from a topic or set of keywords. Use Exact Title Match when you already know the bill title and want a tighter lookup.',
        placement: 'bottom',
      },
      {
        id: 'legislative-tracker-query',
        route: '/app/legislative',
        target: 'legislative-tracker-query',
        title: 'Enter the keyword or topic',
        body: 'Type the policy topic, issue, or bill name here. In broad mode, think in themes or keywords. In exact mode, use the bill title as closely as possible.',
        placement: 'bottom',
      },
      {
        id: 'legislative-tracker-jurisdiction',
        route: '/app/legislative',
        target: 'legislative-tracker-jurisdiction',
        title: 'Choose the jurisdiction',
        body: 'Search federal bills, or switch to a specific state when the legislation you care about is state-level.',
        placement: 'bottom',
      },
      {
        id: 'legislative-tracker-year',
        route: '/app/legislative',
        target: 'legislative-tracker-year',
        title: 'Filter by year',
        body: 'Use the year filter to narrow the search to a specific legislative session or recent cycle. Leave it broad if you want discovery first.',
        placement: 'bottom',
      },
      {
        id: 'legislative-tracker-results-limit',
        route: '/app/legislative',
        target: 'legislative-tracker-results-limit',
        title: 'Control how many bills come back',
        body: 'This controls how many search matches the tool returns. A smaller result set is easier to review quickly, while a larger set is better for broad scanning.',
        placement: 'bottom',
      },
      {
        id: 'legislative-tracker-run',
        route: '/app/legislative',
        target: 'legislative-tracker-submit',
        title: 'Run the search',
        body: 'This starts the bill search. The tour never runs it for you, so the search stays fully manual.',
        placement: 'top',
      },
      {
        id: 'legislative-tracker-results-list',
        route: '/app/legislative',
        title: 'Review the list of bills',
        body: 'These are the bills the search found. For each bill, you can open a quick preview, request a detailed summary, or save it into the watchlist for ongoing tracking.',
        placement: 'center',
        image: '/legislative-tracker-tour-results-list.png',
        imageAlt: 'Legislative Tracker search results list screenshot',
      },
      {
        id: 'legislative-tracker-preview',
        route: '/app/legislative',
        title: 'Use the quick preview first',
        body: 'The preview gives you a fast read on the bill record, a short metadata-based summary, current status, and download options. From here, you can still move into a detailed summary when the bill looks relevant.',
        placement: 'center',
        image: '/legislative-tracker-tour-preview.png',
        imageAlt: 'Legislative Tracker quick preview screenshot',
      },
      {
        id: 'legislative-tracker-detailed',
        route: '/app/legislative',
        title: 'Generate a detailed summary',
        body: 'The detailed summary scans the full bill text and shows a richer, verified synthesis with key provisions, thresholds, dates, exceptions, legislative status, and downloads.',
        placement: 'center',
        image: '/legislative-tracker-tour-detailed-summary.png',
        imageAlt: 'Legislative Tracker detailed summary screenshot',
      },
      {
        id: 'legislative-tracker-watchlist',
        route: '/app/legislative',
        title: 'Track bills in the watchlist',
        body: 'Once a bill is worth following, save it to the watchlist. The watchlist keeps tracked bills together so you can preview them again, refresh their status, or remove them later.',
        placement: 'center',
        image: '/legislative-tracker-tour-watchlist.png',
        imageAlt: 'Legislative Tracker watchlist screenshot',
      },
    ],
  },
  [TOOL_TOUR_IDS.mediaClips]: {
    id: TOOL_TOUR_IDS.mediaClips,
    label: 'Media Clips Tour',
    steps: [
      {
        id: 'media-clips-intro',
        route: '/app/media-clips',
        target: 'media-clips-title-heading',
        title: 'What this tool does',
        body: 'Media Clips searches Google News, collects article candidates, lets you clean the article text, and then turns the reviewed set into a report and email draft.',
        placement: 'bottom',
      },
      {
        id: 'media-clips-title',
        route: '/app/media-clips',
        target: 'media-clips-topic',
        title: 'Title the report',
        body: 'Start by naming the report. This title is used across the clips workflow and helps label the final deliverables.',
        placement: 'bottom',
      },
      {
        id: 'media-clips-keywords',
        route: '/app/media-clips',
        target: 'media-clips-query-builder',
        title: 'Add keywords or Boolean queries',
        body: 'Use simple keywords for a faster search, or switch to Advanced and write Boolean queries with operators like AND, OR, quotes for exact phrases, and exclusions for noise.',
        placement: 'right',
      },
      {
        id: 'media-clips-search-words',
        route: '/app/media-clips',
        target: 'media-clips-keywords-input',
        title: 'Enter the words to search',
        body: 'Type the keywords here when you use Simple mode. If you switch to Advanced, use the query box to write one Boolean search per line.',
        placement: 'bottom',
      },
      {
        id: 'media-clips-filters',
        route: '/app/media-clips',
        target: 'media-clips-filters',
        title: 'Control the search window',
        body: 'Here you choose the research period, target date, source filter, and how many articles to return.',
        placement: 'left',
      },
      {
        id: 'media-clips-run',
        route: '/app/media-clips',
        target: 'media-clips-submit',
        title: 'Run the search',
        body: 'This launches the search and initial cleanup pass. The tour never runs it automatically for you.',
        placement: 'top',
      },
      {
        id: 'media-clips-articles-list',
        route: '/app/media-clips',
        title: 'Review the article list',
        body: 'These are the collected articles. On the left, the red X or green check shows whether the article still needs full-text review or already has usable text. On the right, you can open the source link, review the article, or remove it from the set.',
        placement: 'center',
        image: '/media-clips-tour-articles-list.png',
        imageAlt: 'Media Clips collected articles list screenshot',
      },
      {
        id: 'media-clips-cleaner',
        route: '/app/media-clips',
        title: 'Use the cleaner inside review',
        body: 'Inside the expanded review pane you can paste article text, edit the author, clean the article further, or manually refine the text directly. Whatever stays in this editor is what goes into the final report.',
        placement: 'center',
        image: '/media-clips-tour-cleaner.png',
        imageAlt: 'Media Clips cleaner inside the review articles pane screenshot',
      },
      {
        id: 'media-clips-final-pane',
        route: '/app/media-clips',
        title: 'Build the report and draft the email',
        body: 'This final pane is where you build the report, generate the email draft, download the report files, and prepare the message for sending through Mail.app.',
        placement: 'center',
        image: '/media-clips-tour-final-pane.png',
        imageAlt: 'Media Clips final build and download pane screenshot',
      },
      {
        id: 'media-clips-email-preview',
        route: '/app/media-clips',
        title: 'Preview the email draft',
        body: 'This is the email preview. Use it to review the final draft before downloading the text or HTML version, or before opening the message in Mail.app.',
        placement: 'center',
        image: '/media-clips-tour-email-preview.png',
        imageAlt: 'Media Clips email preview screenshot',
      },
      {
        id: 'media-clips-mail-warning',
        route: '/app/media-clips',
        title: 'Open in Mail.app is Mac-only',
        body: 'This Mail.app handoff works only on macOS. If you are not on a Mac, use the downloadable email draft files instead.',
        placement: 'center',
        image: '/media-clips-tour-mail-warning.png',
        imageAlt: 'Media Clips Mail app warning screenshot',
      },
      {
        id: 'media-clips-save-search',
        route: '/app/media-clips',
        title: 'Save the current research',
        body: 'At the end of the workflow, you can save the current search so the full research setup can be reused later. This is useful when you want to revisit the same monitoring topic without rebuilding the query from scratch.',
        placement: 'center',
        image: '/media-clips-tour-save-search.png',
        imageAlt: 'Media Clips save current search screenshot',
      },
      {
        id: 'media-clips-load-search',
        route: '/app/media-clips',
        title: 'Open previous saved searches',
        body: 'Saved searches appear here. Use this menu to reopen a previous research setup and continue from an earlier Media Clips run.',
        placement: 'center',
        image: '/media-clips-tour-load-search.png',
        imageAlt: 'Media Clips load saved search screenshot',
      },
    ],
  },
  [TOOL_TOUR_IDS.mediaList]: {
    id: TOOL_TOUR_IDS.mediaList,
    label: 'Media List Tour',
    steps: [
      {
        id: 'media-list-intro',
        route: '/app/media-list',
        target: 'media-list-title-heading',
        title: 'What this tool does',
        body: 'Media List builds a targeted press list from a policy issue, scope filters, and media-type preferences, then lets you draft tailored pitches.',
        placement: 'bottom',
      },
      {
        id: 'media-list-issue-step',
        route: '/app/media-list',
        target: 'media-list-issue',
        title: 'Policy issue to pitch',
        body: 'Describe the issue or development you want to pitch so the tool can anchor the search on the right story.',
        placement: 'bottom',
      },
      {
        id: 'media-list-broad-topic-step',
        route: '/app/media-list',
        target: 'media-list-broad-topic',
        title: 'Broad topic',
        body: 'This optional field widens the search into a broader beat when the issue should be framed in a larger policy area.',
        placement: 'bottom',
      },
      {
        id: 'media-list-coverage-desk-step',
        route: '/app/media-list',
        target: 'media-list-coverage-desk',
        title: 'Coverage desk',
        body: 'This optional filter helps the tool target a newsroom desk such as Health, Energy, or Tech.',
        placement: 'bottom',
      },
      {
        id: 'media-list-geographic-step',
        route: '/app/media-list',
        target: 'media-list-geographic-scope',
        title: 'Geographic scope',
        body: 'Choose whether the outreach should focus nationally or on a specific state or metro area.',
        placement: 'bottom',
      },
      {
        id: 'media-list-outlet-step',
        route: '/app/media-list',
        target: 'media-list-outlet-scope',
        title: 'Outlet scope',
        body: 'Use this to limit the search to national outlets only or widen it to all relevant outlets in scope.',
        placement: 'bottom',
      },
      {
        id: 'media-list-num-contacts-step',
        route: '/app/media-list',
        target: 'media-list-num-contacts',
        title: 'Number of contacts',
        body: 'This slider controls how many contacts the tool should try to return.',
        placement: 'left',
      },
      {
        id: 'media-list-types-step',
        route: '/app/media-list',
        target: 'media-list-types',
        title: 'Media types to include',
        body: 'Choose which kinds of outlets and formats should be included in the list.',
        placement: 'left',
      },
      {
        id: 'media-list-run-step',
        route: '/app/media-list',
        target: 'media-list-submit',
        title: 'Build the media list',
        body: 'This runs the media-list workflow. The tour stays passive and never starts it for you.',
        placement: 'top',
      },
      {
        id: 'media-list-summary-step',
        route: '/app/media-list',
        title: 'Output summary',
        body: 'The summary shows how many contacts were requested and returned, the media-type mix, the coverage notes, and the top reporting used to justify the run.',
        placement: 'center',
        image: '/media-list-tour-summary.png',
        imageAlt: 'Media List summary screenshot',
      },
      {
        id: 'media-list-table-step',
        route: '/app/media-list',
        title: 'Full contact table',
        body: 'This table contains the full returned list, including the outlet, role, media type, location, pitch angle, evidence, and pitch action for each contact.',
        placement: 'center',
        image: '/media-list-tour-table.png',
        imageAlt: 'Media List table screenshot',
      },
      {
        id: 'media-list-pitch-button-step',
        route: '/app/media-list',
        title: 'Pitch draft button',
        body: 'Each contact has a pitch action. Open it to generate a personalized outreach draft for that specific journalist.',
        placement: 'center',
        image: '/media-list-tour-pitch-button.png',
        imageAlt: 'Media List pitch draft modal initial state screenshot',
      },
      {
        id: 'media-list-pitch-preview-step',
        route: '/app/media-list',
        title: 'Pitch draft preview',
        body: 'After generation, the pitch modal shows the drafted subject line and body so you can review, regenerate, or copy the outreach text.',
        placement: 'center',
        image: '/media-list-tour-pitch-preview.png',
        imageAlt: 'Media List pitch preview screenshot',
      },
    ],
  },
  [TOOL_TOUR_IDS.messagingMatrix]: {
    id: TOOL_TOUR_IDS.messagingMatrix,
    label: 'Messaging Deliverables Tour',
    steps: [
      {
        id: 'messaging-matrix-intro',
        route: '/app/messaging',
        target: 'messaging-matrix-title-heading',
        title: 'What this tool does',
        body: 'Messaging Deliverables turns a core policy position into a message map and multiple advocacy formats for different audiences and channels.',
        placement: 'bottom',
      },
      {
        id: 'messaging-matrix-position-step',
        route: '/app/messaging',
        target: 'messaging-matrix-position',
        title: 'Core policy position',
        body: 'Start with the policy stance you want every deliverable to reinforce.',
        placement: 'bottom',
      },
      {
        id: 'messaging-matrix-core-messages-step',
        route: '/app/messaging',
        target: 'messaging-matrix-core-messages',
        title: 'Core messages and supporting facts',
        body: 'This optional section lets you supply your own key messages, framing, and proof points instead of relying only on generation.',
        placement: 'left',
      },
      {
        id: 'messaging-matrix-context-step',
        route: '/app/messaging',
        target: 'messaging-matrix-context',
        title: 'Supporting context',
        body: 'Paste context here or attach source files such as reports, memos, or evidence packets to ground the drafts.',
        placement: 'left',
      },
      {
        id: 'messaging-matrix-organization-step',
        route: '/app/messaging',
        target: 'messaging-matrix-organization',
        title: 'Organization name',
        body: 'Add the organization that should appear in the message outputs when relevant.',
        placement: 'bottom',
      },
      {
        id: 'messaging-matrix-audience-step',
        route: '/app/messaging',
        target: 'messaging-matrix-audience',
        title: 'Primary target audience',
        body: 'Use this to steer tone and framing toward the main audience you are trying to reach.',
        placement: 'bottom',
      },
      {
        id: 'messaging-matrix-variants-step',
        route: '/app/messaging',
        target: 'messaging-matrix-variants',
        title: 'Deliverables filtering',
        body: 'Choose which deliverables you want the tool to generate in this run.',
        placement: 'top',
      },
      {
        id: 'messaging-matrix-run-step',
        route: '/app/messaging',
        target: 'messaging-matrix-submit',
        title: 'Generate the deliverables',
        body: 'This starts the workflow. The tour stays passive and never submits for you.',
        placement: 'top',
      },
      {
        id: 'messaging-matrix-message-map-step',
        route: '/app/messaging',
        title: 'Message Map',
        body: 'The message map captures the overarching message, the main supporting pillars, and the key terms that unify the rest of the outputs.',
        placement: 'center',
        image: '/messaging-deliverables-tour-message-map.png',
        imageAlt: 'Messaging Deliverables message map screenshot',
      },
      {
        id: 'messaging-matrix-hill-step',
        route: '/app/messaging',
        title: 'Hill Talking Points',
        body: 'This tab turns the message into legislative talking points with supporting evidence and committee-ready framing.',
        placement: 'center',
        image: '/messaging-deliverables-tour-hill-talking-points.png',
        imageAlt: 'Messaging Deliverables hill talking points screenshot',
      },
      {
        id: 'messaging-matrix-media-step',
        route: '/app/messaging',
        title: 'Media Talking Points',
        body: 'This version adapts the core position into interview-ready talking points, soundbites, and bridge language for media use.',
        placement: 'center',
        image: '/messaging-deliverables-tour-media-talking-points.png',
        imageAlt: 'Messaging Deliverables media talking points screenshot',
      },
      {
        id: 'messaging-matrix-news-release-step',
        route: '/app/messaging',
        title: 'News Release',
        body: 'The news release tab drafts a formal announcement built from the same position and supporting context.',
        placement: 'center',
        image: '/messaging-deliverables-tour-news-release.png',
        imageAlt: 'Messaging Deliverables news release screenshot',
      },
      {
        id: 'messaging-matrix-social-step',
        route: '/app/messaging',
        title: 'Social Media',
        body: 'This tab creates social-ready copy adapted for different platforms, including short-form posts and longer carousel-style drafts.',
        placement: 'center',
        image: '/messaging-deliverables-tour-social-media.png',
        imageAlt: 'Messaging Deliverables social media screenshot',
      },
      {
        id: 'messaging-matrix-grassroots-step',
        route: '/app/messaging',
        title: 'Grassroots Email',
        body: 'The grassroots email tab drafts a supporter-facing message built for mobilization and outreach.',
        placement: 'center',
        image: '/messaging-deliverables-tour-grassroots-email.png',
        imageAlt: 'Messaging Deliverables grassroots email screenshot',
      },
      {
        id: 'messaging-matrix-op-ed-step',
        route: '/app/messaging',
        title: 'Op-Ed Draft',
        body: 'The op-ed draft expands the position into a longer-form argument suitable for external publication after review.',
        placement: 'center',
        image: '/messaging-deliverables-tour-op-ed-draft.png',
        imageAlt: 'Messaging Deliverables op-ed draft screenshot',
      },
      {
        id: 'messaging-matrix-speech-step',
        route: '/app/messaging',
        title: 'Speech Draft',
        body: 'The speech draft turns the same position into a speech-style narrative with a spoken structure and cadence.',
        placement: 'center',
        image: '/messaging-deliverables-tour-speech-draft.png',
        imageAlt: 'Messaging Deliverables speech draft screenshot',
      },
      {
        id: 'messaging-matrix-downloads-step',
        route: '/app/messaging',
        title: 'Download pane',
        body: 'When the run is complete, use these downloads to export the deliverables as Markdown, DOCX, or JSON.',
        placement: 'center',
        image: '/messaging-deliverables-tour-downloads.png',
        imageAlt: 'Messaging Deliverables downloads screenshot',
      },
    ],
  },
  [TOOL_TOUR_IDS.remy]: {
    id: TOOL_TOUR_IDS.remy,
    label: 'Remy Tour',
    steps: [
      {
        id: 'remy-intro',
        route: '/app/remy',
        target: 'remy-title-heading',
        title: 'What Remy can do',
        body: 'Remy can research current news, search the open web, run Legislative Tracker, run Influence Disclosure Tracker, and draft PA documents using the built-in writing style guides.',
        placement: 'bottom',
      },
      {
        id: 'remy-input-step',
        route: '/app/remy',
        target: 'remy-input',
        title: 'Describe the objective',
        body: 'Use the prompt box to describe the task, subject, and desired output. Remy can ask for missing details before researching, running a tool, or drafting a document.',
        placement: 'top',
      },
      {
        id: 'remy-output-step',
        route: '/app/remy',
        target: 'remy-messages',
        title: 'Chat, tool links, and artifacts',
        body: 'The conversation appears here. Remy can return source-linked answers, show tool events, link you to the related tool page, and package written outputs as downloadable Markdown and DOCX files.',
        placement: 'right',
      },
    ],
  },
  [TOOL_TOUR_IDS.stakeholderBriefing]: {
    id: TOOL_TOUR_IDS.stakeholderBriefing,
    label: 'Stakeholder Briefing Tour',
    steps: [
      {
        id: 'stakeholder-briefing-intro',
        route: '/app/stakeholder-briefing',
        target: 'stakeholder-briefing-title-heading',
        title: 'What this tool does',
        body: 'Stakeholder Briefing creates a pre-meeting brief with profile, policy positions, talking points, optional disclosure records, and optional recent news.',
        placement: 'bottom',
      },
      {
        id: 'stakeholder-briefing-name-step',
        route: '/app/stakeholder-briefing',
        target: 'stakeholder-briefing-name',
        title: 'Stakeholder name',
        body: 'Start with the person you are meeting or researching.',
        placement: 'bottom',
      },
      {
        id: 'stakeholder-briefing-organization-step',
        route: '/app/stakeholder-briefing',
        target: 'stakeholder-briefing-organization',
        title: 'Organization',
        body: 'Add the stakeholder’s organization, office, committee, or institutional affiliation when it helps anchor the brief.',
        placement: 'bottom',
      },
      {
        id: 'stakeholder-briefing-purpose-step',
        route: '/app/stakeholder-briefing',
        target: 'stakeholder-briefing-meeting-purpose',
        title: 'Meeting purpose',
        body: 'Describe the purpose of the meeting so the brief can orient around the right issue and objectives.',
        placement: 'right',
      },
      {
        id: 'stakeholder-briefing-options-step',
        route: '/app/stakeholder-briefing',
        target: 'stakeholder-briefing-options',
        title: 'Additional options',
        body: 'Here you can add your organization, write extra context, attach supporting files, and decide whether to include disclosure and news research.',
        placement: 'left',
      },
      {
        id: 'stakeholder-briefing-run-step',
        route: '/app/stakeholder-briefing',
        target: 'stakeholder-briefing-submit',
        title: 'Generate the briefing',
        body: 'This runs the briefing workflow. The tour stays passive and never starts it for you.',
        placement: 'top',
      },
      {
        id: 'stakeholder-briefing-profile-step',
        route: '/app/stakeholder-briefing',
        title: 'Profile and questions to ask',
        body: 'The Profile tab gives you the stakeholder summary, role, key policy areas, notable positions, and suggested questions to ask in the meeting.',
        placement: 'center',
        image: '/stakeholder-briefing-tour-profile.png',
        imageAlt: 'Stakeholder Briefing profile screenshot',
      },
      {
        id: 'stakeholder-briefing-policy-step',
        route: '/app/stakeholder-briefing',
        title: 'Policy positions',
        body: 'The Policy Positions tab summarizes the positions most relevant to your meeting, with evidence and why each position matters.',
        placement: 'center',
        image: '/stakeholder-briefing-tour-policy-positions.png',
        imageAlt: 'Stakeholder Briefing policy positions screenshot',
      },
      {
        id: 'stakeholder-briefing-talking-points-step',
        route: '/app/stakeholder-briefing',
        title: 'Talking points',
        body: 'The Talking Points tab turns the research into practical points to raise during the meeting, each with a short rationale.',
        placement: 'center',
        image: '/stakeholder-briefing-tour-talking-points.png',
        imageAlt: 'Stakeholder Briefing talking points screenshot',
      },
      {
        id: 'stakeholder-briefing-news-step',
        route: '/app/stakeholder-briefing',
        title: 'News',
        body: 'When news search is enabled, the News tab surfaces recent coverage linked to the stakeholder and lets you open the source articles directly.',
        placement: 'center',
        image: '/stakeholder-briefing-tour-news.png',
        imageAlt: 'Stakeholder Briefing news screenshot',
      },
      {
        id: 'stakeholder-briefing-downloads-step',
        route: '/app/stakeholder-briefing',
        title: 'Downloads',
        body: 'The final pane lets you export the briefing as Markdown, DOCX, or JSON.',
        placement: 'center',
        image: '/stakeholder-briefing-tour-downloads.png',
        imageAlt: 'Stakeholder Briefing downloads screenshot',
      },
    ],
  },
  [TOOL_TOUR_IDS.stakeholderMap]: {
    id: TOOL_TOUR_IDS.stakeholderMap,
    label: 'Stakeholder Map Tour',
    steps: [
      {
        id: 'stakeholder-map-intro',
        route: '/app/stakeholders',
        target: 'stakeholder-map-title-heading',
        title: 'What this tool does',
        body: 'Stakeholder Map identifies actors around a policy issue and organizes them into a network and strategic analysis view.',
        placement: 'bottom',
      },
      {
        id: 'stakeholder-map-issue-step',
        route: '/app/stakeholders',
        target: 'stakeholder-map-issue',
        title: 'Policy issue',
        body: 'Enter the policy issue or debate area you want the map to center on.',
        placement: 'bottom',
      },
      {
        id: 'stakeholder-map-types-step',
        route: '/app/stakeholders',
        target: 'stakeholder-map-types',
        title: 'Actor types to include',
        body: 'These checkboxes control which types of actors are included in the map.',
        placement: 'left',
      },
      {
        id: 'stakeholder-map-build-step',
        route: '/app/stakeholders',
        target: 'stakeholder-map-submit',
        title: 'Build the stakeholder map',
        body: 'This runs the mapping pipeline. The tour stays passive and never starts it for you.',
        placement: 'top',
      },
      {
        id: 'stakeholder-map-summary-step',
        route: '/app/stakeholders',
        title: 'Initial output summary',
        body: 'After completion, the first output surface shows the run status, the verification warning, and the top summary counts for actors and relationships.',
        placement: 'center',
        image: '/stakeholder-map-tour-summary.png',
        imageAlt: 'Stakeholder Map initial output summary screenshot',
      },
      {
        id: 'stakeholder-map-network-overview-step',
        route: '/app/stakeholders',
        title: 'Network Analysis (I)',
        body: 'The first part of Network Analysis gives you the high-level strategic readout and the engagement priority lists for top opponents, top proponents, and persuadables.',
        placement: 'center',
        image: '/stakeholder-map-tour-network-overview.png',
        imageAlt: 'Stakeholder Map network analysis overview screenshot',
      },
      {
        id: 'stakeholder-map-network-metrics-step',
        route: '/app/stakeholders',
        title: 'Network Analysis (II)',
        body: 'The second part of Network Analysis shows which actors connect the network, which ones have the widest reach, and the structural metrics that describe the shape of the map.',
        placement: 'center',
        image: '/stakeholder-map-tour-network-metrics.png',
        imageAlt: 'Stakeholder Map network metrics screenshot',
      },
      {
        id: 'stakeholder-map-strategy-overview-step',
        route: '/app/stakeholders',
        title: 'Strategic Analysis (I)',
        body: 'The first part of Strategic Analysis summarizes the power landscape, highlights the key dynamics shaping the issue, and lists the most immediate actions to consider.',
        placement: 'center',
        image: '/stakeholder-map-tour-strategy-overview.png',
        imageAlt: 'Stakeholder Map strategic analysis overview screenshot',
      },
      {
        id: 'stakeholder-map-strategy-detail-step',
        route: '/app/stakeholders',
        title: 'Strategic Analysis (II)',
        body: 'The second part of Strategic Analysis maps coalition opportunities, the main risks, the recommended swing actor strategy, the broader issue overview, and the known coalitions already visible in the landscape.',
        placement: 'center',
        image: '/stakeholder-map-tour-strategy-detail.png',
        imageAlt: 'Stakeholder Map strategic analysis detail screenshot',
      },
      {
        id: 'stakeholder-map-proponents-step',
        route: '/app/stakeholders',
        title: 'Proponents',
        body: 'This tab summarizes the proponent coalition and lists the actors currently mapped as supporting the issue, along with their confidence, influence tier, and strategic relevance.',
        placement: 'center',
        image: '/stakeholder-map-tour-proponents.png',
        imageAlt: 'Stakeholder Map proponents screenshot',
      },
      {
        id: 'stakeholder-map-opponents-step',
        route: '/app/stakeholders',
        title: 'Opponents',
        body: 'This tab summarizes the opposition coalition and lists the actors currently mapped as opposing the issue, together with their influence and strategic relevance.',
        placement: 'center',
        image: '/stakeholder-map-tour-opponents.png',
        imageAlt: 'Stakeholder Map opponents screenshot',
      },
      {
        id: 'stakeholder-map-all-actors-step',
        route: '/app/stakeholders',
        title: 'All actors',
        body: 'This table brings the full map together in one view so you can review every discovered actor, their source type, stance, confidence, and strategic relevance in a single place.',
        placement: 'center',
        image: '/stakeholder-map-tour-all-actors.png',
        imageAlt: 'Stakeholder Map all actors screenshot',
      },
      {
        id: 'stakeholder-map-downloads-step',
        route: '/app/stakeholders',
        title: 'Downloads',
        body: 'The final pane lets you export the stakeholder map in spreadsheet, document, markdown, and JSON formats.',
        placement: 'center',
        image: '/stakeholder-map-tour-downloads.png',
        imageAlt: 'Stakeholder Map downloads screenshot',
      },
    ],
  },
};
