export const TOUR_STORAGE_KEY = 'strategitect_guided_tour_completed';

export const REVIEWER_TOUR_ID = 'reviewer-tour';

export const TOOL_TOUR_IDS = {
  backgroundMemo: 'tool-background-memo',
  hearingMemo: 'tool-hearing-memo',
  influenceTracker: 'tool-influence-tracker',
  legislativeTracker: 'tool-legislative-tracker',
  mediaClips: 'tool-media-clips',
  mediaList: 'tool-media-list',
  messagingMatrix: 'tool-messaging-matrix',
  remy: 'tool-remy',
  stakeholderBriefing: 'tool-stakeholder-briefing',
  stakeholderMap: 'tool-stakeholder-map',
};

function buildToolTour({ id, title, route, introTarget, introBody, inputTarget, inputTitle, inputBody, optionalTarget, optionalTitle, optionalBody, submitTarget, submitBody, outputTarget, outputBody }) {
  return {
    id,
    label: title,
    steps: [
      {
        id: `${id}-intro`,
        route,
        target: introTarget,
        title,
        body: introBody,
        placement: 'bottom',
      },
      {
        id: `${id}-input`,
        route,
        target: inputTarget,
        title: inputTitle,
        body: inputBody,
        placement: 'bottom',
      },
      {
        id: `${id}-optional`,
        route,
        target: optionalTarget,
        title: optionalTitle,
        body: optionalBody,
        placement: 'left',
      },
      {
        id: `${id}-submit`,
        route,
        target: submitTarget,
        title: 'Run it yourself',
        body: submitBody,
        placement: 'top',
      },
      {
        id: `${id}-output`,
        route,
        target: outputTarget,
        title: 'Output surface',
        body: outputBody,
        placement: 'top',
      },
    ],
  };
}

export const TOUR_DEFINITIONS = {
  [REVIEWER_TOUR_ID]: {
    id: REVIEWER_TOUR_ID,
    label: 'Guided Reviewer Tour',
    steps: [
      {
        id: 'dashboard-overview',
        route: '/app',
        target: 'dashboard-overview',
        title: 'How the prototype is organized',
        body: 'These sections group tools by workflow stage: intelligence gathering, stakeholder preparation, and output creation.',
        placement: 'bottom',
      },
      {
        id: 'dashboard-background-memo',
        route: '/app',
        target: 'background-memo-card',
        title: 'Recommended starting point',
        body: 'Background Memo is the fastest review path because the input is simple and the output shows the system logic clearly.',
        placement: 'right',
      },
      {
        id: 'background-subject',
        route: '/app/background-memo',
        target: 'background-memo-subject',
        title: 'Start with a clear subject',
        body: 'Use an organization, issue, or person. Broad but recognizable entries like "NATO" or "Pfizer" work well for a first run.',
        placement: 'bottom',
      },
      {
        id: 'background-sections',
        route: '/app/background-memo',
        target: 'background-memo-sections',
        title: 'Define the memo structure',
        body: 'Write one section per line. This tells the tool how to organize the briefing instead of changing the underlying research logic.',
        placement: 'right',
      },
      {
        id: 'background-options',
        route: '/app/background-memo',
        target: 'background-memo-options',
        title: 'Optional grounding inputs',
        body: 'Context, source files, and disclosure settings deepen the memo, but they are not required for a simple reviewer demo.',
        placement: 'left',
      },
      {
        id: 'background-submit',
        route: '/app/background-memo',
        target: 'background-memo-submit',
        title: 'Run the pipeline manually',
        body: 'The tour never submits for you. When you are ready, this button starts the backend job with exactly the inputs you entered.',
        placement: 'top',
      },
      {
        id: 'background-output',
        route: '/app/background-memo',
        target: 'background-memo-output',
        title: 'What appears after a run',
        body: 'Status, generated memo content, downloads, and supporting materials show up here. Outputs remain review-required before external use.',
        placement: 'top',
      },
      {
        id: 'tour-complete',
        route: '/app/background-memo',
        title: 'Tour complete',
        body: 'You can now run Background Memo, return to the dashboard, or explore the rest of the toolkit and Remy freely.',
        placement: 'center',
      },
    ],
  },
  [TOOL_TOUR_IDS.backgroundMemo]: buildToolTour({
    id: TOOL_TOUR_IDS.backgroundMemo,
    title: 'Background Memo Tour',
    route: '/app/background-memo',
    introTarget: 'tour-button-background-memo',
    introBody: 'Use this tool to turn a subject plus section outline into a structured first-draft briefing.',
    inputTarget: 'background-memo-subject',
    inputTitle: 'Choose the subject',
    inputBody: 'Enter a recognizable organization, issue, or individual. Keep it specific enough that the memo can anchor on one subject.',
    optionalTarget: 'background-memo-options',
    optionalTitle: 'Optional grounding',
    optionalBody: 'Context, files, and disclosure settings strengthen the result but are not required for a quick reviewer run.',
    submitTarget: 'background-memo-submit',
    submitBody: 'The tour explains the screen only. This button keeps the normal manual submission flow unchanged.',
    outputTarget: 'background-memo-output',
    outputBody: 'This area shows status first, then memo sections, supporting materials, and downloads when the job finishes.',
  }),
  [TOOL_TOUR_IDS.hearingMemo]: buildToolTour({
    id: TOOL_TOUR_IDS.hearingMemo,
    title: 'Hearing Memo Tour',
    route: '/app/memos',
    introTarget: 'tour-button-hearing-memo',
    introBody: 'Hearing Memo turns a transcript source into a verified, house-style first draft with review signals.',
    inputTarget: 'hearing-memo-source',
    inputTitle: 'Provide a transcript source',
    inputBody: 'Upload a hearing transcript or provide a YouTube URL. One reliable source is enough for a first pass.',
    optionalTarget: 'hearing-memo-options',
    optionalTitle: 'Metadata and overrides',
    optionalBody: 'Advanced options help shape the memo header and hearing metadata, but the core flow works without them.',
    submitTarget: 'hearing-memo-submit',
    submitBody: 'Submission remains manual so the tour never changes what gets sent to the backend.',
    outputTarget: 'hearing-memo-output',
    outputBody: 'You will see pipeline status, verification flags, memo preview, and download options in this output block.',
  }),
  [TOOL_TOUR_IDS.influenceTracker]: buildToolTour({
    id: TOOL_TOUR_IDS.influenceTracker,
    title: 'Influence Tracker Tour',
    route: '/app/influence',
    introTarget: 'tour-button-influence-tracker',
    introBody: 'Influence Tracker searches disclosure systems and organizes the matches into reviewable tables and exports.',
    inputTarget: 'influence-tracker-entities',
    inputTitle: 'List the entities to search',
    inputBody: 'Enter one or more entities you want to investigate. Separate multiple entities by line or comma, depending on your usual workflow.',
    optionalTarget: 'influence-tracker-options',
    optionalTitle: 'Scope and source filters',
    optionalBody: 'These controls narrow years, quarters, sources, and thresholds. Leave them broad for a quick exploratory search.',
    submitTarget: 'influence-tracker-submit',
    submitBody: 'Running the tool preserves the existing disclosure lookup logic and matching thresholds.',
    outputTarget: 'influence-tracker-output',
    outputBody: 'The results area shows status, structured disclosure tables, and export actions once records are returned.',
  }),
  [TOOL_TOUR_IDS.legislativeTracker]: buildToolTour({
    id: TOOL_TOUR_IDS.legislativeTracker,
    title: 'Legislative Tracker Tour',
    route: '/app/legislative',
    introTarget: 'tour-button-legislative-tracker',
    introBody: 'Legislative Tracker helps reviewers move from a bill search to summaries and watchlist tracking.',
    inputTarget: 'legislative-tracker-query',
    inputTitle: 'Start with a bill topic',
    inputBody: 'Use a bill title or keywords, then choose jurisdiction and year only if you need to narrow the search.',
    optionalTarget: 'legislative-tracker-results',
    optionalTitle: 'Search results and summary actions',
    optionalBody: 'After a search, you can preview a bill, request a detailed summary, or add it to the watchlist.',
    submitTarget: 'legislative-tracker-submit',
    submitBody: 'The primary action here is the bill search. Follow-up summary actions remain manual and unchanged.',
    outputTarget: 'legislative-tracker-output',
    outputBody: 'This section shows search status first, then bill details, summaries, diagnostics, and downloads.',
  }),
  [TOOL_TOUR_IDS.mediaClips]: buildToolTour({
    id: TOOL_TOUR_IDS.mediaClips,
    title: 'Media Clips Tour',
    route: '/app/media-clips',
    introTarget: 'tour-button-media-clips',
    introBody: 'Media Clips searches news coverage, lets you review extracted text, and rebuilds the final report.',
    inputTarget: 'media-clips-topic',
    inputTitle: 'Define the report',
    inputBody: 'Start with a report topic and either simple keywords or Boolean queries, depending on how precise you want the search to be.',
    optionalTarget: 'media-clips-clip-cleaner',
    optionalTitle: 'Cleaner and review tools',
    optionalBody: 'The clip cleaner and article editor let you refine text before rebuilding the final report, but they are optional.',
    submitTarget: 'media-clips-submit',
    submitBody: 'The tool still runs only when you choose to submit your search.',
    outputTarget: 'media-clips-output',
    outputBody: 'The output area shows job status, article review controls, report rebuild actions, and downloads.',
  }),
  [TOOL_TOUR_IDS.mediaList]: buildToolTour({
    id: TOOL_TOUR_IDS.mediaList,
    title: 'Media List Tour',
    route: '/app/media-list',
    introTarget: 'tour-button-media-list',
    introBody: 'Media List turns an issue and targeting filters into a draft outreach list with downloadable formats.',
    inputTarget: 'media-list-issue',
    inputTitle: 'Describe the issue',
    inputBody: 'Give the tool a policy issue or pitch topic. Add broad topic or desk inputs when you want the search to widen.',
    optionalTarget: 'media-list-options',
    optionalTitle: 'Targeting filters',
    optionalBody: 'Location, contact count, media type, and source filter help you shape the list without changing the core workflow.',
    submitTarget: 'media-list-submit',
    submitBody: 'The generation step remains manual so you stay in control of what the tool searches for.',
    outputTarget: 'media-list-output',
    outputBody: 'Results appear here as a contact table, optional pitch drafting actions, and export downloads.',
  }),
  [TOOL_TOUR_IDS.messagingMatrix]: buildToolTour({
    id: TOOL_TOUR_IDS.messagingMatrix,
    title: 'Messaging Deliverables Tour',
    route: '/app/messaging',
    introTarget: 'tour-button-messaging-matrix',
    introBody: 'Messaging Deliverables converts a policy position into a message map and multiple draft formats.',
    inputTarget: 'messaging-matrix-position',
    inputTitle: 'Anchor on the core position',
    inputBody: 'Start with the organization’s actual stance. The rest of the drafting system builds from that position.',
    optionalTarget: 'messaging-matrix-options',
    optionalTitle: 'Optional message support',
    optionalBody: 'Core messages, facts, context, and deliverable selection help shape the outputs, but the position remains the main input.',
    submitTarget: 'messaging-matrix-submit',
    submitBody: 'The tour does not populate or submit anything. It only points you to the live controls.',
    outputTarget: 'messaging-matrix-output',
    outputBody: 'This panel shows the generated message map, variant drafts, and the available download formats.',
  }),
  [TOOL_TOUR_IDS.remy]: buildToolTour({
    id: TOOL_TOUR_IDS.remy,
    title: 'Remy Tour',
    route: '/app/remy',
    introTarget: 'tour-button-remy',
    introBody: 'Remy is the orchestration layer: you describe the objective, and it routes work or gathers missing inputs.',
    inputTarget: 'remy-input',
    inputTitle: 'Describe the objective',
    inputBody: 'A good first prompt states the task, subject, and any specific sections or deliverables you want.',
    optionalTarget: 'remy-messages',
    optionalTitle: 'Conversation and tool events',
    optionalBody: 'Remy replies in the chat and can surface tool events or artifact links inline when it uses a module.',
    submitTarget: 'remy-submit',
    submitBody: 'The send button keeps the existing chat behavior unchanged.',
    outputTarget: 'remy-messages',
    outputBody: 'This conversation area is the output: messages, tool routing, artifact links, and any follow-up prompts.',
  }),
  [TOOL_TOUR_IDS.stakeholderBriefing]: buildToolTour({
    id: TOOL_TOUR_IDS.stakeholderBriefing,
    title: 'Stakeholder Briefing Tour',
    route: '/app/stakeholder-briefing',
    introTarget: 'tour-button-stakeholder-briefing',
    introBody: 'Stakeholder Briefing prepares a pre-meeting brief with profile, positions, disclosure context, and talking points.',
    inputTarget: 'stakeholder-briefing-name',
    inputTitle: 'Identify the stakeholder',
    inputBody: 'Enter the person and meeting purpose first. Those two fields drive the briefing structure.',
    optionalTarget: 'stakeholder-briefing-options',
    optionalTitle: 'Additional context',
    optionalBody: 'Optional context, files, and disclosure/news toggles deepen the briefing but are not required for a quick run.',
    submitTarget: 'stakeholder-briefing-submit',
    submitBody: 'The button still performs the normal briefing job only when you choose to run it.',
    outputTarget: 'stakeholder-briefing-output',
    outputBody: 'This output area contains the generated tabs, verification flags, and export options.',
  }),
  [TOOL_TOUR_IDS.stakeholderMap]: buildToolTour({
    id: TOOL_TOUR_IDS.stakeholderMap,
    title: 'Stakeholder Map Tour',
    route: '/app/stakeholders',
    introTarget: 'tour-button-stakeholder-map',
    introBody: 'Stakeholder Map finds actors around an issue and organizes them into a network and strategic analysis view.',
    inputTarget: 'stakeholder-map-issue',
    inputTitle: 'Set the issue',
    inputBody: 'Use a policy issue or debate area, not a person. The map works best when the issue is specific but broad enough to have multiple actors.',
    optionalTarget: 'stakeholder-map-types',
    optionalTitle: 'Choose actor types',
    optionalBody: 'These checkboxes shape the map coverage. Leave them broad if you want the fullest first pass.',
    submitTarget: 'stakeholder-map-submit',
    submitBody: 'The build action stays manual and uses the existing mapping pipeline unchanged.',
    outputTarget: 'stakeholder-map-output',
    outputBody: 'This output surface shows status first, then network results, strategic views, and export actions.',
  }),
};
